# Generated by Django 4.2.4 on 2023-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id телеграм чата'),
        ),
    ]
