# Generated by Django 4.2.4 on 2023-08-21 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время выполнения')),
                ('lead_time_in_seconds', models.PositiveIntegerField(verbose_name='время на выполнения в секундах')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения привычки')),
                ('periodicity', models.CharField(choices=[(1, 'каждый день'), (2, 'каждые два дня'), (3, 'каждые три дня'), (4, 'каждые четыре дня'), (5, 'каждые пять дней'), (6, 'каждые шесть дней'), (7, 'каждые семь дней')], max_length=50)),
                ('deed', models.CharField(max_length=150, verbose_name='действие привычки')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('is_enjoyable_habit', models.BooleanField(default=False, verbose_name='это приятная привычка')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('connected_enjoyable_habit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enjoyable_habit', to='habits.habit', verbose_name='приятная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
