# Generated by Django 4.2.4 on 2023-08-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='connected_enjoyable_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enjoyable_habit', to='habits.habit', verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='deed',
            field=models.CharField(max_length=150, verbose_name='привычка'),
        ),
    ]
