# Generated by Django 4.2.4 on 2023-08-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_connected_enjoyable_habit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='lead_time_in_seconds',
            new_name='duration_in_seconds',
        ),
    ]
