# Generated by Django 4.2.4 on 2023-08-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.PositiveIntegerField(verbose_name='id чата телеграм')),
            ],
            options={
                'verbose_name': 'подключенный чат',
                'verbose_name_plural': 'подключенный чат',
            },
        ),
    ]
