# Generated by Django 4.2.4 on 2023-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_conn', '0003_alter_connectedchats_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_data', models.TextField(verbose_name='данные сообщения')),
            ],
            options={
                'verbose_name': 'обработанное сообщение ',
                'verbose_name_plural': 'обработанные сообщения',
            },
        ),
    ]
