# Generated by Django 4.2.4 on 2023-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_conn', '0004_processedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedmessage',
            name='message_data',
            field=models.TextField(unique=True, verbose_name='данные сообщения'),
        ),
    ]
