# Generated by Django 4.2.4 on 2023-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_conn', '0006_delete_connectedchats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedmessage',
            name='message_data',
            field=models.JSONField(unique=True, verbose_name='данные сообщения'),
        ),
    ]
